### ISSUE TITLE
Newcomers_Guide.rst: Rephrase note

### ISSUE THREAD

**Issue by Makman2** [coala/documentation#183]
> ```
> .. note::
> 
>     Reviewing code helps you by watching other people's mistakes and not making
>     them yourself in the future!
> ```

Imo it should also contain something in the direction of "you are improving yourself doing this" :+1:

**Comment by Dayfiri** [comment]
Assign me please :)

**Comment by sils** [comment]
Hey,

you have done two newcomer issues and it seems you're well acquainted with the workflow! That's awesome :)

We recommend to not do newcomer issues anymore because they take us more time to file than to fix them - let other newcomers can have a few as well. The next level for you are the [low difficulty issues](http://tinyurl.com/coala-low) - you can now dive into whatever you want. Let us know if you need help or have any special interests - there's a lot of stuff going on and usually interests can be met :)

Cheers!

**Comment by Dayfiri** [comment]
@sils Ok thanks for the info. I will do that in the future 👍

**Comment by sils** [comment]
See coala.io/low there should be plenty of easy stuff to go on with

**Comment by Akki356** [comment]
Please Assign me this :)

**Comment by Adrianzatreanu** [comment]
hey first please accept the invitation, join us on gitter! https://gitter.im/coala/coala

**Comment by Adrianzatreanu** [comment]
unassigning due to inactivity

**Comment by MihneaVorovenci** [comment]
Can I be assigned on this issue?

**Comment by Mariatta** [comment]
This issue was moved to coala/coala#3254
