### ISSUE TITLE
Add link to bash/zsh autocompletion in installation guide

### ISSUE THREAD

**Issue by sils** [coala/documentation#386]
difficulty newcomer

Some sentence and a link to the page which explains how to setup autocompletion would be helping users looking for that.

**Comment by vedantrathore** [comment]
@sils can I work on it? Also where should I read more about bash/zsh autocompletion?

**Comment by adtac** [comment]
@vedantrathore sure, assigned you :+1:

>Also where should I read more about bash/zsh autocompletion?

Google is your friend ;)

**Comment by thotayashwanth123** [comment]
Hi, I want to assign this issue.

**Comment by all3fox** [comment]
Looks like the users' guide already has a link to `argcomplete`, look here just under the `pip install argcomplete` lline: https://docs.coala.io/en/latest/Users/Shell_Autocompletion.html

Do you want the newcomers' guide to duplicate that? I would disagree: it's not really essential for newcomers, is it? It could also become an obstacle because it's tricky to make it work, see #388 

Suggesting to close the issue.

**Comment by saurabhraj1896** [comment]
can i work on this issue?
